//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESys.Notification.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESys.Notification.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 启动 的本地化字符串。
        /// </summary>
        internal static string Assign {
            get {
                return ResourceManager.GetString("Assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批量 的本地化字符串。
        /// </summary>
        internal static string Batch {
            get {
                return ResourceManager.GetString("Batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ： 的本地化字符串。
        /// </summary>
        internal static string Colon {
            get {
                return ResourceManager.GetString("Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成 的本地化字符串。
        /// </summary>
        internal static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ！ 的本地化字符串。
        /// </summary>
        internal static string Exclamation {
            get {
                return ResourceManager.GetString("Exclamation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 yyyy-MM-dd HH:mm:ss 的本地化字符串。
        /// </summary>
        internal static string FormatterDatetime {
            get {
                return ResourceManager.GetString("FormatterDatetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 频率 的本地化字符串。
        /// </summary>
        internal static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锁定账户 的本地化字符串。
        /// </summary>
        internal static string HeaderAccountLockedAccount {
            get {
                return ResourceManager.GetString("HeaderAccountLockedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尝试登录次数 的本地化字符串。
        /// </summary>
        internal static string HeaderAccountLockedAttamptCount {
            get {
                return ResourceManager.GetString("HeaderAccountLockedAttamptCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锁定时间 的本地化字符串。
        /// </summary>
        internal static string HeaderAccountLockedTimestamp {
            get {
                return ResourceManager.GetString("HeaderAccountLockedTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 签名账户 的本地化字符串。
        /// </summary>
        internal static string HeaderESignAccount {
            get {
                return ResourceManager.GetString("HeaderESignAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 签名时间 的本地化字符串。
        /// </summary>
        internal static string HeaderESignTimestamp {
            get {
                return ResourceManager.GetString("HeaderESignTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录账户 的本地化字符串。
        /// </summary>
        internal static string HeaderLoginFailureAccount {
            get {
                return ResourceManager.GetString("HeaderLoginFailureAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误信息 的本地化字符串。
        /// </summary>
        internal static string HeaderLoginFailureMessage {
            get {
                return ResourceManager.GetString("HeaderLoginFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录时间 的本地化字符串。
        /// </summary>
        internal static string HeaderLoginFailureTimestamp {
            get {
                return ResourceManager.GetString("HeaderLoginFailureTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 （ 的本地化字符串。
        /// </summary>
        internal static string LeftParentheses {
            get {
                return ResourceManager.GetString("LeftParentheses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 限度超限 的本地化字符串。
        /// </summary>
        internal static string LimitOverrun {
            get {
                return ResourceManager.GetString("LimitOverrun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列表 的本地化字符串。
        /// </summary>
        internal static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码无效 的本地化字符串。
        /// </summary>
        internal static string MessageLoginFailureCodeError {
            get {
                return ResourceManager.GetString("MessageLoginFailureCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户被禁用 的本地化字符串。
        /// </summary>
        internal static string MessageLoginFailureForbidden {
            get {
                return ResourceManager.GetString("MessageLoginFailureForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有权限 的本地化字符串。
        /// </summary>
        internal static string MessageLoginFailureNotAuthorized {
            get {
                return ResourceManager.GetString("MessageLoginFailureNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户不存在 的本地化字符串。
        /// </summary>
        internal static string MessageLoginFailureNotExist {
            get {
                return ResourceManager.GetString("MessageLoginFailureNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 令牌过期 的本地化字符串。
        /// </summary>
        internal static string MessageLoginFailureTokenExpired {
            get {
                return ResourceManager.GetString("MessageLoginFailureTokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码错误 的本地化字符串。
        /// </summary>
        internal static string MessageLoginFailureWrongPassword {
            get {
                return ResourceManager.GetString("MessageLoginFailureWrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 月 的本地化字符串。
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未 的本地化字符串。
        /// </summary>
        internal static string Not {
            get {
                return ResourceManager.GetString("Not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目 的本地化字符串。
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ） 的本地化字符串。
        /// </summary>
        internal static string RightParentheses {
            get {
                return ResourceManager.GetString("RightParentheses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 样本条码 的本地化字符串。
        /// </summary>
        internal static string SampleBarcode {
            get {
                return ResourceManager.GetString("SampleBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计划日期 的本地化字符串。
        /// </summary>
        internal static string ScheduledDate {
            get {
                return ResourceManager.GetString("ScheduledDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账户锁定 的本地化字符串。
        /// </summary>
        internal static string SubjectAccountLocked {
            get {
                return ResourceManager.GetString("SubjectAccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的电子签名 的本地化字符串。
        /// </summary>
        internal static string SubjectInvalidESign {
            get {
                return ResourceManager.GetString("SubjectInvalidESign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录失败 的本地化字符串。
        /// </summary>
        internal static string SubjectLoginFailure {
            get {
                return ResourceManager.GetString("SubjectLoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务 的本地化字符串。
        /// </summary>
        internal static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地点名称 的本地化字符串。
        /// </summary>
        internal static string TestLocation {
            get {
                return ResourceManager.GetString("TestLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测方法 的本地化字符串。
        /// </summary>
        internal static string TestMethod {
            get {
                return ResourceManager.GetString("TestMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采样点名称 的本地化字符串。
        /// </summary>
        internal static string TestSite {
            get {
                return ResourceManager.GetString("TestSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当天 的本地化字符串。
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户 的本地化字符串。
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 周 的本地化字符串。
        /// </summary>
        internal static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
    }
}
